create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;
create schema auth; create schema storage; create schema extensions;
grant usage on schema public, auth, storage, extensions to anon, authenticated, service_role;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true),''),'{}')::jsonb $$;
create function auth.role() returns text language sql stable as $$ select current_user::text $$;
create function auth.gen_salt(text) returns text language sql as $$ select 'salt' $$;
create function auth.crypt(text,text) returns text language sql as $$ select md5($1) $$;
create function extensions.crypt(text,text) returns text language sql as $$ select md5($1) $$;
create function extensions.gen_salt(text) returns text language sql as $$ select 'salt' $$;
grant execute on all functions in schema auth to anon, authenticated;
create table auth.users (instance_id uuid, id uuid primary key, aud text, role text, email text, encrypted_password text, email_confirmed_at timestamptz, raw_user_meta_data jsonb default '{}', created_at timestamptz, updated_at timestamptz, last_sign_in_at timestamptz, banned_until timestamptz);
create table storage.objects (id serial, bucket_id text, name text); alter table storage.objects enable row level security;
create policy "Allow admins to upload documents" on storage.objects for insert to authenticated with check (bucket_id='documents' and ((auth.jwt()->'user_metadata')->>'role')='admin');
create table public.profiles (id uuid primary key, username text, full_name text, avatar_url text, role text default 'user', permissions jsonb default '{}'::jsonb, banned_until timestamptz, theme text);
alter table public.profiles enable row level security;
create policy "Admins can manage user profiles" on public.profiles for update to authenticated using ((select p1.role from profiles p1 where p1.id=auth.uid())='admin') with check (true);
create policy "sel" on public.profiles for select to authenticated using (true);
create policy "ins" on public.profiles for insert to authenticated with check (auth.uid()=id);
create policy "Allow user to update their own profile" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);
create function public.get_my_role() returns text language sql stable as $$ select role from public.profiles where id = auth.uid() $$;
create function public.is_staff() returns boolean language plpgsql security definer as $$ begin return (auth.jwt()->'user_metadata'->>'role') in ('admin','moderator'); end $$;
create table public.infractions (id uuid default gen_random_uuid() primary key, user_id uuid, admin_id uuid, card_type text, reason text, expires_at timestamptz, is_active boolean default true);
do $$ declare t text; begin foreach t in array array['chauffeurs_bus','contacts_bus','contacts_repertoire','ligne_data','lignes_bus','pn_data','societes_bus','spi_data','taxis','changelog','pmr_clients','pmr_data','procedures','ebp','app_settings','b201_reports','darts_games','temp_geo_data','liaisons_contenu','remise_bus','remise_taxi','remise_intervention','remise_pmr'] loop
 execute format('create table public.%I (id serial primary key, key text unique, value text, updated_at timestamptz)', t); end loop; end $$;
create table public.main_courante (id serial, user_id uuid);
create table public.audit_logs (id serial, "timestamp" timestamptz, action_type text, table_name text, record_id text, changes text, user_id uuid);
create view public.admin_audit_view as select a.id, p.full_name from audit_logs a left join profiles p on a.user_id=p.id;
do $$ declare t text; begin foreach t in array array['archive_procedure','handle_new_mention_notification','handle_procedure_update','handle_updated_at','handle_updated_at_with_user','log_audit_action','log_audit_diff'] loop
 execute format('create function public.%I() returns trigger language plpgsql security definer as $f$ begin return new; end $f$', t); end loop; end $$;
create function public.sync_user_role() returns trigger language plpgsql security definer as $$ begin update auth.users set raw_user_meta_data = raw_user_meta_data || jsonb_build_object('role', new.role) where id=new.id; return new; end $$;
create trigger on_profile_role_change after update of role on public.profiles for each row execute function public.sync_user_role();
create function public.handle_new_user() returns trigger language plpgsql security definer as $$ begin insert into public.profiles(id, username) values (new.id, split_part(new.email,'@',1)); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.admin_create_user(new_email text, new_role text, new_password text) returns json language plpgsql security definer as $$ begin return null; end $$;
create function public.admin_set_ban_status(user_id_to_modify uuid, should_ban boolean) returns json language plpgsql security definer as $$ begin return null; end $$;
create function public.admin_pardon_infraction(p_infraction_id uuid) returns void language plpgsql security definer as $$ begin end $$;
create function public.admin_add_infraction(target_user_id uuid, p_card_type text, p_reason text, duration_months_if_yellow integer default 6) returns json language plpgsql security definer as $$ begin return null; end $$;
create function public.get_all_users() returns table(user_id uuid, email text, role text, full_name text, avatar_url text, last_sign_in_at timestamptz, banned_until timestamptz, active_yellow_cards bigint, active_red_cards bigint) language plpgsql security definer as $$ begin end $$;
create function public.global_search(search_term text) returns setof int language sql as $$ select 1 $$;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema storage to anon, authenticated;
grant usage on all sequences in schema public, storage to anon, authenticated;
grant execute on all functions in schema public to anon, authenticated;
insert into auth.users(id,email) values ('00000000-0000-0000-0000-00000000000a','admin@x'),('00000000-0000-0000-0000-00000000000b','user@x');
update public.profiles set role='admin' where id='00000000-0000-0000-0000-00000000000a';
insert into public.app_settings(key,value) values ('maintenance_mode','false');
